### PR TITLE
Fixed UI elements appearing white in dark mode

### PR DESCRIPTION
**Pull request by simone-kalbermatter**
This PR addresses issue https://github.com/dedis/popstellar/issues/1381.
The change disables dark mode in each activity. However, it is not very clean and we could consider implementing a dark mode theme instead.
It was manually tested on the emulator.

### CODE REVIEW

**Review by matteosz — COMMENTED** [review]
I don't have any specific suggestions, as for now I think it's clean enough.

Either way, creating our own dark mode is a great idea for future directions, perhaps included in a settings tab with other customizable options.

**Review by matteosz — DISMISSED** [review]

**Review by Warhedgehog — CHANGES_REQUESTED** [review]
Good job ! Since this is a "temporary" fixes, you should add a line of comments that explain what this does and why.

**Review by jbsv — DISMISSED** [review]
LGTM (looks good to me) well done

**Comment by jbsv** [comment]
agree with @Warhedgehog to add a comment

**Review by pierluca — APPROVED** [review]
LGTM (@Warhedgehog I've asked for your review to remove the "changes requested")

**Review by Warhedgehog — APPROVED** [review]
LGTM (sorry for the delay)

**Pull request merged**
