### PR TITLE
Refactor Karate Part 1

### PR DESCRIPTION
**Pull request by simone-kalbermatter**
This PR makes the Karate tests more readable by removing all `JSON.stringify` calls.

### CODE REVIEW

**Review by matteosz — APPROVED** [review]
LGTM! Nice refactoring, the method `JSON.stringify` was just impacting on the tests readability

**Review by Warhedgehog — COMMENTED** [review]
So the `JSON.stringify` was completely useless ?

**Comment by simone-kalbermatter** [comment]
@Warhedgehog Yes, the `JSON.stringify` was useless, it was probably just used because it was easier to work with strings directly instead of converting json maps in `MultiMsgWebSocketClient`. For example, because it extends `WebSocketClient`, it inherits a `send(String msg)` function.

**Review by Warhedgehog — APPROVED** [review]
LGTM

**Pull request merged**
