### PR TITLE
Fix app crash when trying to launch an LAO without a server running

### PR DESCRIPTION
**Pull request by Warhedgehog**
Previous implementation tried to toasts displayed by callback function on the thread the callback was executed on. This cause crashes. Toasts can only be showed by the UI thread. This fixes the bug by forcing the toast only to be executed by the UI thread.

This solves #881

### CODE REVIEW

**Review by Tesa27 — APPROVED** [review]
Definitely a problem good catch!

**Review by jbsv — COMMENTED** [review]
As I I don't see any restriction in the Android [documentation](https://developer.android.com/reference/android/widget/Toast#makeText(android.content.Context,%20int,%20int)) I wonder if the "context" passed to the function is always correct ?

**Comment by Warhedgehog** [comment]
From https://stackoverflow.com/questions/5018545/getapplication-vs-getapplicationcontext:
"Although in current Android Activity and Service implementations, getApplication() and getApplicationContext() return the same object, there is no guarantee that this will always be the case (for example, in a specific vendor implementation)."

This could indicate that it is better to replace `getApplication()` with `getApplication().getApplicationContext()` 


For avoiding having a null context : 
From https://developer.android.com/reference/android/content/Context#getApplicationContext():
"Return the context of the single, global Application object of the current process. This generally should only be used if you need a Context whose lifecycle is separate from the current context, that is tied to the lifetime of the process rather than the current component."

From my understanding it should be fine. I've tested with what used to crash but go into settings before the toast is displayed and it behaves as expected.

What do you think ?

**Comment by jbsv** [comment]
Hmmm, so could we just use 'getApplication().getApplicationContext()' when context is null to avoid crashing ? or do we get another error which is an unexpected behaviour (like not displaying the toast) ? In which case I would stick with the proposed fix, indeed.
Alternatively, you might want to give the [snackbar](https://developer.android.com/training/snackbar/) a quick try.

**Comment by GabrielFleischer** [comment]
To me the current implementation seems completely fine.
From my expirience, the context is only used to know where in view hierachy the Toast should be displayed. And that's way there is no real restriction on the input context. There is no reason to as long as the context is part of the application, it will work fine.

And as @Warhedgehog pointed out, the `context` should never be `null`. And in the rare case it is, we probably have bigger problems to consider.

The probable only safer way to implement this is to create a new Service centered around the creation of Toast. It would have access to the Application context at startup. That way we are always sure that the context is valid.

I approve this PR as I don't see any reason not to.

**Review by GabrielFleischer — APPROVED** [review]
LGTM

**Pull request merged**
