### PR TITLE
Fix digital cash float input

### LINKED ISSUE #1160: [BUG] Trying to send or issue a float number crashes the app
### Description (Actual behavior)
Issuing or sending a float number of coin results in a crash 

### Expected behavior
Ideal behavior would be not to let the user select a non integer amount. But at least the app should gracefully deal with a float input.

### How to reproduce
1. Create an LAO and conduct a valid and complete roll-call
2. Navigate to digital cash
3. Navigate to issue
4. Issue 42.1 coins
5. See crash

### Version & Environment
This bug was reproduced on:
- Commit: [257330f](https://github.com/dedis/popstellar/commit/257330f033352207db2feeb0d6f68bbba60f1289)
##### Front-ends:
- [ ] Fe1-Web (please include browser's names & version)
- [x] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [x] Not applicable

##### Environment (as applicable):
 - Device: [e.g. Pixel 4 XL emulator on Windows 10]
 - OS: [Windows 10]

### Workaround
Only input integers for issuance and send

### Impact
A unsuspecting user could trigger a crash which is to be avoided.

### PR DESCRIPTION
**Pull request by Warhedgehog**
This fixes #1160

### CODE REVIEW

**Comment by jbsv** [comment]
does this allow float input like "123.45" ?

**Comment by Warhedgehog** [comment]
No. I did not fix the parsing, I prevented the input from containing anything other than "0-9"

**Comment by lourkeur** [comment]
Can confirm the comma button is greyed out on Samsung SM-G950F

**Review by zoemarin — APPROVED** [review]
Oh parfait !

**Pull request merged**
