### PR TITLE
Reset chirp text after publishing

### LINKED ISSUE #1013: [FE1] Chirp field does not clear after posting
### Description (Actual behavior)
After sending the chirp, the same content stays in the text field.
screen

### Expected behavior
The field should clear if the chirp has been successfully posted.

### How to reproduce
1. Obtain pop token
2. Go to social media
3. Post chirp
4. See the same text

### Version & Environment
This bug was reproduced on:
- 2022-05-10 pop party

##### Front-ends:
- [x] Fe1-Web (please include browser's names & version)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [x] Not applicable

##### Environment (as applicable):
- Firefox 100.0
- NixOS Linux 22.05.20220505.c777cdf
- HP 470 G7

### Workaround
Erase manually after chirping

### Impact
Makes it easy to accidentally double posts, breaks UI expectations

### PR DESCRIPTION
**Pull request by Tyratox**
Fixes #1013

### CODE REVIEW

**Review by lourkeur — APPROVED** [review]
Good fix
image

**Review by 0xdieman — APPROVED** [review]
LGTM

**Review by Xelowak — DISMISSED** [review]
LGTM! That's a nice change we wanted to add last semester but in the end we didn't have the time for it, so thanks a lot.

**Review by Xelowak — APPROVED** [review]
Thanks for the tests!

**Pull request merged**
