### PR TITLE
Display attendee pop token when trying to join roll call

### PR DESCRIPTION
**Pull request by dayan9265**
This PR makes that now the pop token is also displayed in clear text in case the organizer can't use his camera. I added some space between the qr code and the text in case the attendee doesn't want the organizer to see the text he can simply zoom on the qr code et let the text be outside of the screen. 

image

### CODE REVIEW

**Review by MeKHell — APPROVED** [review]
Looks good to me. I just added a small question.

**Comment by dayan9265** [comment]
> Looks good to me. I just added a small question.

I can't seem to find your question, what was it?

**Comment by pierluca** [comment]
@Tyratox @Xelowak are either of you available to review ?

**Review by Tyratox — DISMISSED** [review]
LGTM :)

**Comment by Tyratox** [comment]
Although I‘d use a monospace font for consistency 😅

**Comment by dayan9265** [comment]
Ah yes true, I added the monospace font :)

**Review by Tyratox — APPROVED** [review]
👍😁

**Pull request merged**
