### PR TITLE
Rework LAO Event screen part 1

### PR DESCRIPTION
**Pull request by Tyratox**
This PR is a first step in the direction we want to move with the lao (events) UI. This PR removes / hides the identity screen, moves the button showing the lao connection code to the events screen and puts the information that previously was accessible by clicking on the laos name with the circled i icon (the lao properties) into the same screen where the connection qr code can be found. At the moment I do not like the look of this screen. Partially because there is not enough spacing between the text and qr code but even with that it feels a bit off. The qr code is centered which makes it look better in a browser but on a narrow screen the non-alignment with the rest seems a bit weird to me. Does anybody have an idea on how to improve this?

Moreover the X button for disconnecting from the lao was replaced by a standard back button. Lastly in this PR, the way to access the notification screen was changed. Previously there was a bell button on the identity screen next to the lao connection qr code, now it is placed in the tab navigation bar since there now is space there given the removal of the identity screen.

In a next PR I will work on the past / current / future sections.

Any thoughts? :)

Screenshot 2022-10-27 at 10 51 16

Screenshot 2022-10-30 at 11 07 09

### CODE REVIEW

**Comment by Tyratox** [comment]
Now also fixes #1213 by replacing the "Done" with an X and properly aligning it :)

**Comment by Tyratox** [comment]
Also fixes #1214 by removing the two buttons as the first one is not needed yet and the functionality of the second was replicated (pressing the back button in the top navbar does the same)

**Comment by Tyratox** [comment]
Now also takes care of https://github.com/dedis/popstellar/issues/1215 by removing the circled i, making the left and right headers take up as much space as they need, shrink the title if needed and restrict the title to one line (and all ... if it exceeds the available space)

**Review by pierluca — APPROVED** [review]
No particular remarks, this looks pretty good already 👍

**Pull request merged**
